GET http://localhost:8080/api/locations

###
GET http://localhost:8080/api/locations/2

###
DELETE http://localhost:8080/api/locations/1

###
POST http://localhost:8080/api/locations/
Content-type: application/json

{
    "latitude": 60,
    "longitude": 120
}